language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t thepatrvq/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thepatrvq/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Docker-env'
  buck_name: 'elasticbeanstalk-us-east-2-185135932904'
  buck_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
