FROM node:alpine

WORKDIR /app

COPY package.json .
# RUN apk add --no-cache bash coreutils grep sed
# RUN npm install pm2 -g
RUN npm i
COPY ./ ./

CMD ["npm", "run", "start"]
# CMD ["pm2-runtime", "npm", "--", "start"]